"""courses and assessments

Revision ID: 88b98ba66c9d
Revises: 5de672a7382c
Create Date: 2025-10-26 16:39:41.547332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b98ba66c9d'
down_revision = '5de672a7382c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coursename', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('assessment_number', sa.Integer(), nullable=False),
    sa.Column('class_weight', sa.Float(), nullable=False),
    sa.Column('exam_weight', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_user_id'), ['user_id'], unique=False)

    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessmentname', sa.String(length=140), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('mark', sa.Float(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_course_id'))

    op.drop_table('assessment')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_timestamp'))

    op.drop_table('course')
    # ### end Alembic commands ###
